export const redirect = {
  afterhours: 'https://afterhours.dscvit.com',
  dscid:
    'https://medium.com/gdg-vit/how-to-handle-imbalanced-datasets-d33d10678c8a?source=friends_link&sk=45f724429b0dc51eb2846bf05c18af9f',
  community: 'https://gdsc.community.dev/vellore-institute-of-technology-vit-vellore/',
  insta: 'https://www.instagram.com/gdscvitvellore/',
  linkedin: 'https://www.linkedin.com/company/dscvit',
  twitter: 'https://twitter.com/gdscvit',
  youtube: 'https://www.youtube.com/channel/UCvT-ZJF7fXHJi9kDeCPR-zg',
  resources: 'https://resources.dscvit.com',
  discord: 'https://discord.gg/4VqH3RJQXG',
  telegram:'https://t.me/joinchat/Zlq0k9DMj6cxYTQ9',
  fb:'https://www.facebook.com/gdscvitvellore',
  'org-monster': 'https://chrome.google.com/webstore/detail/org-monster/egilbonoajnapajkbihnalficajlomcn',
  camp2: 'https://dsc.community.dev/e/m4ht92/',
  minimalism: 'https://medium.com/@aroranamya5/dial-down-the-minimalism-77f8dc0d9641',
  camp3:
    'https://dsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-presents-git-going-with-github-devcamp/',
  blogonlinecollege:
    'https://medium.com/gdg-vit/pandemic-online-classes-everything-else-5a483d1423e5?source=friends_link&sk=877ec26afabaab4dde97444f9bec6f5c',
  camp4:
    'https://dsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-presents-jetset-javascript-devcamp/',
  flutterday2020: 'https://www.youtube.com/playlist?list=PLiI1-GFGRl4sL1lurgBvJZUMxxi6_gRcQ',
  nodeyt: 'https://www.youtube.com/playlist?list=PLiI1-GFGRl4tVZcWZvdqw44XbIjBNXn0p',
  androidstudy: 'https://www.youtube.com/playlist?list=PLiI1-GFGRl4ufZkSeSUP5qv7j21lyY_sQ',
  mlrandomnessblog:
    'https://medium.com/gdg-vit/understanding-the-role-of-randomness-in-machine-learning-4a19632f41c4?source=friends_link&sk=4714e51d2e4c1b060d8e593c9b4c2a8f',
  camp5:
    'https://dsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-presents-build-with-react-devcamp/',
  getstartedblog:
    'https://medium.com/gdg-vit/5-tips-to-get-you-started-developeredition-bccfc2adf9ff?source=friends_link&sk=7cb75db17e668baaced0c1815b643bdd',
  notebooksmaster:
    'https://medium.com/gdg-vit/my-kaggle-journey-from-novice-to-notebooks-masters-92bb4dc51a89',
  songifiedandcyanite:
    'https://medium.com/gdg-vit/songified-and-cyanite-1cdb187b4168?source=friends_link&sk=f8ea2324bdf0cde8f1194f3388ea4ce6',
  'vitty-app':
    'https://play.google.com/store/apps/details?id=com.dscvit.vitty',
  'vitty-extension':
    'https://chrome.google.com/webstore/detail/vitty/eeohmkjefmpmddidkjadpifbfcplkifh',
  vitty: 'https://vitty.dscvit.com',
  ep6reg:'https://www.youtube.com/watch?v=RV_24cI6GJE&feature=youtu.be',
  searchengine:'https://medium.com/gdg-vit/a-guide-to-understanding-search-engines-b83f12132722',
  notifierblog:'https://medium.com/gdg-vit/notifier-bot-be892baaf445?source=friends_link&sk=57c01e86a29f3d79c29d3ffaeb883c44',
  backendblog:'https://medium.com/gdg-vit/which-backend-stack-should-you-learn-e4935dfe81bd?source=friends_link&sk=166633a73e76a8e7328420d594f1c798',
  tensorflowblog:'https://medium.com/gdg-vit/my-journey-of-becoming-a-tensorflow-certified-developer-9ba6134807b5?source=friends_link&sk=8dfe2284188ae7ab62cc5142eaf2a631',
  camp6: 'https://gdsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-presents-workshop-on-advanced-react/',
  hackjudgeblog:'https://medium.com/gdg-vit/hackjudge-from-inception-to-application-af92c0221f04?source=friends_link&sk=df3f0f46ce03ecc9e00be7239aeabd85',
  camp7:'https://gdsc.community.dev/e/mn2qht/',
  camp8:'https://gdsc.community.dev/e/mz6uzv/',
  pipoblog:'https://medium.com/gdg-vit/pipo-the-journey-from-ideation-to-creation-78e91e1e892d?source=friends_link&sk=ee4abd91c78841c87418ea39014c7ee6',
  camp9:'https://gdsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-vit-vellore-presents-intro-to-ml-devcamp/',
  gcptelegram:'https://t.me/joinchat/nFUPhgOIUbQ5OTQ1',
  gcpreg:'https://events.withgoogle.com/30daysofgooglecloud/#content',
  introgcp:'https://gdsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-vit-vellore-presents-introduction-to-gcp/',
  gcpsession2:'https://gdsc.community.dev/events/details/developer-student-clubs-vellore-institute-of-technology-vit-vellore-presents-introduction-to-deployment-using-gcp-devcamp/',
  'privacy-policy': 'https://docs.google.com/document/d/1f3lusjbR8cS-VC7V2slK1vRaeqONORs_-wC2QLPLBnE/edit',
  dj21blog:'https://medium.com/@ananyageorge019/622a73dc879e?source=friends_link&sk=1be5d89c03b9c490aa74ce719f69e476',
  dj21appios:'https://apps.apple.com/in/app/devjams21/id1593244374',
  ggsblog:'https://pragati1610.medium.com/62f9ec7db091?source=friends_link&sk=dbe13e17f0d66f1a6ecab00fa8c53353',
  asj1:'https://gdsc.community.dev/e/mbht9m/',
  asj21tele:'https://t.me/+DBFst-naM2xkNzRl',
  asj2:'https://gdsc.community.dev/e/mrzrrb/',
  asj3:'https://gdsc.community.dev/e/mn929x/',
  dnblog:'https://medium.com/@kushojha1209/e95287253c86?source=friends_link&sk=3e9ac615eaec7f9f2abf4e1459b15925',
  dj21build:'https://gdsc.community.dev/e/m4jtwh/',
  rc22:'https://gdsc.community.dev/e/mmcvzw/',
  rc22blog: 'https://medium.com/@asthajha05/e06112160c48?source=friends_link&sk=04f71ba53dfb45f3f65ef3f17b9ef614 ',
  vittyblog:'https://medium.com/gdg-vit/vitty-from-an-idea-to-a-reality-25bed956bee9?source=friends_link&sk=acb90ba267e9c083428d050cd30b64f8',
  sc1:'https://gdsc.community.dev/e/m52puj/',
}
