#!/bin/sh
commit_message=$(cat "$1" | sed -e 's/^[[:space:]]*//')
matched_str=$(echo "$commit_message" | grep -E "^Merge.+|(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|types)(\(.+\))?!?: [a-zA-Z0-9 ]+$")
echo "$matched_str"
if [ "$matched_str" != "" ];
then
	exit 0
else
	echo "Commit rejected due to incorrect commit message format. See commit standards here - https://www.conventionalcommits.org/en/v1.0.0/"
	exit 1
fi
